apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: plnf6289b-python 
  janus-idp.io/tekton: plnf6289b-python
  backstage.io/kubernetes-id: plnf6289b-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: plnf6289b-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml